variable "account_id" {
  description = "(Required) The account id that is used to generate the service account email address and a stable unique id. It is unique within a project, must be 6-30 characters long, and match the regular expression [a-z]([-a-z0-9]*[a-z0-9]) to comply with RFC1035. Changing this forces a new service account to be created"
  type        = string
  default     = ""
}

variable "display_name" {
  description = "(Optional) The display name for the service account. Can be updated without creating a new resource"
  default     = ""
  type        = string
}

variable "description" {
  description = "(Optional) A text description of the service account. Must be less than or equal to 256 UTF-8 bytes"
  default     = ""
  type        = string
}

variable "disabled" {
  description = "(Optional) Whether a service account is disabled or not. Defaults to false. This field has no effect during creation. Must be set after creation to disable a service account"
  default     = false
  type        = bool
}

variable "roles" {
  description = "(Required) The role that should be applied. Only one google_service_account_iam_binding can be used per role. Note that custom roles must be of the format [projects|organizations]/{parent-name}/roles/{role-name}"
  type        = list(string)
}

variable "members" {
  description = "(Required) Identities that will be granted the privilege in role"
  type        = list(string)
}

variable "condition" {
  description = "(Optional) An IAM Condition for a given binding"
  type = list(object({
    title       = optional(string)
    description = optional(string)
    expression  = string
  }))
  default = []
}

variable "keys" {
  description = "(Optional) The algorithm used to generate the key. KEY_ALG_RSA_2048 is the default algorithm. Valid values are listed at ServiceAccountPrivateKeyType (only used on create)"
  type = list(object({
    key_create       = optional(string)
    key_algorithm    = optional(string)
    public_key_type  = optional(string)
    private_key_type = optional(string)
    public_key_data  = optional(string)
    rotation_days    = number
  }))
  default = []
}

#variable "key_create" {
#  description = "(Optional) The algorithm used to generate the key. KEY_ALG_RSA_2048 is the default algorithm. Valid values are listed at ServiceAccountPrivateKeyType (only used on create)"
#  type        = bool
#  default     = true
#}
#
#variable "key_algorithm" {
#  description = "(Optional) The algorithm used to generate the key. KEY_ALG_RSA_2048 is the default algorithm. Valid values are listed at ServiceAccountPrivateKeyType (only used on create)"
#  type        = string
#  default     = "KEY_ALG_RSA_2048"
#  validation {
#    condition     = contains(["KEY_ALG_UNSPECIFIED", "KEY_ALG_RSA_1024", "KEY_ALG_RSA_2048"], var.key_algorithm)
#    error_message = "Allowed values for input_parameter are \"KEY_ALG_UNSPECIFIED\", \"KEY_ALG_RSA_1024\", or \"KEY_ALG_RSA_2048\"."
#  }
#}
#
#variable "public_key_type" {
#  description = "(Optional) The output format of the public key requested. TYPE_X509_PEM_FILE is the default output format."
#  type        = string
#  default     = "TYPE_X509_PEM_FILE"
#}
#
#variable "private_key_type" {
#  description = "(Optional) The output format of the private key. TYPE_GOOGLE_CREDENTIALS_FILE is the default output format."
#  type        = string
#  default     = "TYPE_GOOGLE_CREDENTIALS_FILE"
#  validation {
#    condition = contains([
#      "TYPE_UNSPECIFIED", "TYPE_PKCS12_FILE", "TYPE_GOOGLE_CREDENTIALS_FILE"
#    ], var.private_key_type)
#    error_message = "Allowed values for input_parameter are \"TYPE_UNSPECIFIED\", \"TYPE_PKCS12_FILE\", or \"TYPE_GOOGLE_CREDENTIALS_FILE\"."
#  }
#}
#
#variable "public_key_data" {
#  description = "(Optional) Public key data to create a service account key for given service account. The expected format for this field is a base64 encoded X509_PEM and it conflicts with public_key_type and private_key_type."
#  type        = string
#  default     = ""
#}
#
#variable "rotation_days" {
#  description = "(Optional) Arbitrary map of values that, when changed, will trigger a new key to be generated."
#  type        = number
#  default     = 30
#}

variable "policies" {
  description = "(Required only by google_service_account_iam_policy) The policy data generated by a google_iam_policy data source"
  type        = list(string)
}